### ISSUE TITLE
Double Licensing

### ISSUE THREAD

**Issue by hernandev** [rustwasm/rust_wasm_template#3]
Hello, I got curious to understand why this template is released under a double Apache/MIT license.

Thank you!

**Comment by fitzgen** [comment]
Hi! It is simply the most common licensing scheme in the Rust community, and is what the Rust compiler itself is also licensed under.

**Comment by hernandev** [comment]
Thank you for your kind explanation @fitzgen. I will keep the license on the project I'm using this.

Thank you.
